name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up universe ubuntu repo
        run: sudo add-apt-repository universe
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-14
          cmake: true
          ninja: true
      - name: print gcc version
        run: gcc --version
      - name: install Ninja
        run: sudo apt-get install -y ninja-build
      - name: run cmake
        run: cmake -B build -G Ninja -DCOMB_BUILD_TESTS=ON
      - name: build
        run: CXX=g++ CC=gcc cmake --build build
      - name: test
        run: build/comb_tests
