name: Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install Ninja
        run: sudo apt-get install -y ninja-build
      - name: run cmake
        run: cmake -B build -G Ninja -DCOMB_BUILD_TESTS=ON
      - name: build
        run: cmake --build build
      - name: test
        run: build/comb_tests
